#title: AVERtek # your name photo (or website title) here
logo1: "images/HelloAgain_Logo-CMYK-4.png? raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <h3 style="color:#E67360;"><b><p style="font-family:Brandon Grotesque Medium">CANNABIS-POWERED SUPPOSITORY</p></h3></b>
  <h3 style="color:#E67360;"><b><p style="font-family:Brandon Grotesque Medium">FORMULATED FOR MENOPAUSE</p></h3></b>
  <h3 style="color:#E67360;"><b><p style="font-family:Brandon Grotesque Medium">HELPING WOMEN OF ALL AGES</p></h3></b>
  <br>
  <br>
  <h2 style="color:#6B82FF;"><b><a href="https://helloagainproducts.com/?utm_source=AVERtek&utm_medium=QR&utm_campaign=Info&utm_content=WebsiteHome" onclick="getOutboundLink('https://helloagainproducts.com/?utm_source=AVERtek&utm_medium=QR&utm_campaign=Info&utm_content=WebsiteHome'); return false;"</b><b><p style="font-family:Brandon Grotesque Medium">HELLOAGAINPRODUCTS.COM</p></b></a></h2> 
  <br>
  <h2 style="color:#6B82FF;"><b><a href="https://helloagainproducts.com/wp-content/uploads/2021/03/HELLO-AGAIN-LAUNCH.mp4?utm_source=Why%20Us&utm_medium=Video&utm_campaign=XR-NOW&utm_content=PoP" onclick="getOutboundLink('https://helloagainproducts.com/wp-content/uploads/2021/03/HELLO-AGAIN-LAUNCH.mp4?utm_source=Why%20Us&utm_medium=Video&utm_campaign=XR-NOW&utm_content=PoP'); return false;"</b><b><p style="font-family:Brandon Grotesque Medium"> WATCH THIS.</p></b></a></h2> 
  <br> 
  <h2 style="color:#6B82FF;"><b><a href="https://helloagainproducts.com/faq/?utm_source=FAQ&utm_medium=marketing&utm_campaign=XR-NOW&utm_content=point%20of%20purchase" onclick="getOutboundLink('https://helloagainproducts.com/faq/?utm_source=FAQ&utm_medium=marketing&utm_campaign=XR-NOW&utm_content=point%20of%20purchase'); return false;"</b><b><p style="font-family:Brandon Grotesque Medium"> WANT TO KNOW MORE?</p></b></a></h2> 
  <br>
theme: jekyll-theme-minimal
# Google Analytics
google_analytics: UA-000000000-0 
